export const tShirts = [
  {
    id: "T0",
    company: "Angor",
    name: "Plain Black",
    price: 10,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/black_0.png",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "solid", "plain", "men", "male"],
  },
  {
    id: "T1",
    company: "Angor",
    name: "Plain Yellow",
    price: 10,
    type: "short sleeve",
    color: "yellow",
    image: "/tshirts/yellow_0.png",
    tags: ["yellow", "tshirt", "t shirt", "short sleeve", "solid", "plain", "men", "male"],
  },
  {
    id: "T2",
    company: "Angor",
    name: "Route 66",
    price: 15,
    type: "short sleeve",
    color: "blue",
    image: "/tshirts/blue_0.png",
    tags: ["blue", "tshirt", "t shirt", "short sleeve", "route", "men", "male"],
  },
  {
    id: "T3",
    company: "Wildspark",
    name: "Reflective Performance Outdoor",
    price: 20,
    type: "short sleeve",
    color: "green",
    image: "/tshirts/wildSpark.jpg",
    tags: ["green", "tshirt", "t shirt", "short sleeve", "men", "male"],
  },
  {
    id: "T4",
    company: "Kliegou",
    name: "Hipster Premium",
    price: 25,
    type: "short sleeve",
    color: "grey",
    image: "/tshirts/hipsterPremium.jpg",
    tags: ["grey", "tshirt", "t shirt", "short sleeve", "men", "hip-hop", "male"],
  },
  {
    id: "T5",
    company: "Warrior Distressed",
    name: "Skull America",
    price: 20,
    type: "short sleeve",
    color: "red",
    image: "/tshirts/warriorDistressed.jpg",
    tags: ["red", "tshirt", "t shirt", "short sleeve", "men", "male"],
  },
  {
    id: "T6",
    company: "Generic",
    name: "Thankful Rainbow",
    price: 15,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/thankful.jfif",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T7",
    company: "Generic",
    name: "Casual Dressy",
    price: 10,
    type: "short sleeve",
    color: "pink",
    image: "/tshirts/casualDressy.jpg",
    tags: ["pink", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T8",
    company: "Amazon Aware",
    name: "Perfect Long-Sleeve",
    price: 10,
    type: "long sleeve",
    color: "red",
    image: "/tshirts/perfectLongSleeve.jpg",
    tags: ["red", "tshirt", "t shirt", "long sleeve", "women", "female"],
  },
  {
    id: "T9",
    company: "Generic",
    name: "Fall Floral",
    price: 15,
    type: "long sleeve",
    color: "white",
    image: "/tshirts/fallFloral.jpg",
    tags: ["white", "tshirt", "t shirt", "floral", "long sleeve", "women", "female"],
  },
  {
    id: "T10",
    company: "Nautica",
    name: "Nautica White",
    price: 10,
    type: "short sleeve",
    color: "white",
    image: "/tshirts/nauticaWhite.jpg",
    tags: ["white", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T11",
    company: "Nlife",
    name: "Bring on the Sunshine",
    price: 15,
    type: "short sleeve",
    color: "yellow",
    image: "/tshirts/bringOnTheSunshine.jpg",
    tags: ["yellow", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female"],
  },
];

export const pants = [
  {
    id: "P0",
    company: "Angor",
    name: "Jogger Pants",
    price: 20,
    type: "drawstring",
    color: "black",
    image: "/pants/black_0.png",
    tags: ["black", "pants", "drawstring", "jogger", "men", "male"],
  },
  {
    id: "P1",
    company: "Angor",
    name: "Cargo Pants",
    price: 15,
    type: "cargo",
    color: "brown",
    image: "/pants/brown_0.png",
    tags: ["brown", "pants", "cargo", "pockets", "men", "male"],
  },
  {
    id: "P2",
    company: "Angor",
    name: "Formal Pants",
    price: 20,
    type: "formal",
    color: "blue",
    image: "/pants/blue_0.png",
    tags: ["blue", "pants", "formal", "men", "male"],
  },
];

export const caps = [
  {
    id: "C0",
    company: "Angor",
    name: "Classic Grey ",
    price: 10,
    type: "classic",
    color: "grey",
    image: "/caps/grey_0.png",
    tags: ["grey", "cap", "classic", "men", "male"],
  },
  {
    id: "C1",
    company: "Angor",
    name: "Canvas Cap ",
    price: 20,
    type: "canvas",
    color: "blue",
    image: "/caps/blue_0.png",
    tags: ["blue", "cap", "canvas", "men", "male"],
  },
  {
    id: "C2",
    company: "Angor",
    name: "Crew Cap ",
    price: 15,
    type: "crew",
    color: "purple",
    image: "caps/purple_0.png",
    tags: ["purple", "cap", "crew", "men", "male"],
  },
];
