export const tShirts = [
  {
    id: "T0",
    company: "Angor",
    name: "Plain Black",
    price: 10,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/black_0.png",
    description: "This lightweight t-shirt is sweat-absorbent and breathable, so you can feel comfortable and sweat free in the summer.",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "solid", "plain", "men", "male"],
  },
  {
    id: "T1",
    company: "Angor",
    name: "Plain Yellow",
    price: 10,
    type: "short sleeve",
    color: "yellow",
    image: "/tshirts/yellow_0.png",
    description: "Our t-shirt is made of bamboo viscose and cotton combined fabric, which is softer and more breathable than other combination t-shirts.",
    tags: ["yellow", "tshirt", "t shirt", "short sleeve", "solid", "plain", "men", "male"],
  },
  {
    id: "T2",
    company: "Angor",
    name: "Route 66",
    price: 15,
    type: "short sleeve",
    color: "blue",
    image: "/tshirts/blue_0.png",
    description:
      "A workwear staple, this men's pocket t-shirt is equal parts durable and comfortable. It has an original fit, Carhartt's roomiest cut. The heavyweight fabric only gets softer with time.",
    tags: ["blue", "tshirt", "t shirt", "short sleeve", "route", "men", "male"],
  },
  {
    id: "T3",
    company: "Wildspark",
    name: "Reflective Performance Outdoor",
    price: 20,
    type: "short sleeve",
    color: "green",
    image: "/tshirts/wildSpark.jpg",
    description: "5.2-oz. medium-weight cotton for exceptional softness against your skin that gets softer with each washing.",
    tags: ["green", "tshirt", "t shirt", "short sleeve", "men", "male"],
  },
  {
    id: "T4",
    company: "Kliegou",
    name: "Hipster Premium",
    price: 25,
    type: "short sleeve",
    color: "grey",
    image: "/tshirts/hipsterPremium.jpg",
    description:
      "Bamboo Rayon Undershirts: Made from Bamboo Rayon--a kind of cellulose fiber extracted from bamboo. It is featured with good air permeability, instant moisture wicking, lightweight and stable dyeing property.",
    tags: ["grey", "tshirt", "t shirt", "short sleeve", "men", "hip-hop", "male"],
  },
  {
    id: "T5",
    company: "Warrior Distressed",
    name: "Skull America",
    price: 20,
    type: "short sleeve",
    color: "red",
    image: "/tshirts/warriorDistressed.jpg",
    description: "Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, and comfort.",
    tags: ["red", "tshirt", "t shirt", "short sleeve", "men", "male"],
  },
  {
    id: "T6",
    company: "Generic",
    name: "Thankful Rainbow",
    price: 15,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/thankful.jfif",
    description: "Charged Cotton has the comfort of cotton, but dries much faster 4-way stretch construction moves better in every direction.",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T7",
    company: "Generic",
    name: "Casual Dressy",
    price: 10,
    type: "short sleeve",
    color: "pink",
    image: "/tshirts/casualDressy.jpg",
    description:
      "Lightweight cotton blend provides premium softness wash after wash dri-power moisture wicking technology keeps you cool and dry odor protection helps to keep fabric fresh.",
    tags: ["pink", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T8",
    company: "Amazon Aware",
    name: "Perfect Long-Sleeve",
    price: 10,
    type: "long sleeve",
    color: "red",
    image: "/tshirts/perfectLongSleeve.jpg",
    description: "Machine Wash Warm Gentle Cycle. Colors Separately. Only Non-Chlorine Bleach When Needed. Tumble Dry Low. Do not use fabric softener.",
    tags: ["red", "tshirt", "t shirt", "long sleeve", "women", "female"],
  },
  {
    id: "T9",
    company: "Generic",
    name: "Fall Floral",
    price: 15,
    type: "long sleeve",
    color: "white",
    image: "/tshirts/fallFloral.jpg",
    description: "Lightweight tri-blend fabric feels incredibly soft and luxe.",
    tags: ["white", "tshirt", "t shirt", "floral", "long sleeve", "women", "female"],
  },
  {
    id: "T10",
    company: "Nautica",
    name: "Nautica White",
    price: 10,
    type: "short sleeve",
    color: "white",
    image: "/tshirts/nauticaWhite.jpg",
    description:
      "SUPERIOR COMFORT FIT - Our classic crewneck pocket tee is made of 100% heavyweight, soft jersey-knit cotton. Extra-strong taped shoulder & neck seams for added durability. Tagless labeling eliminates chafing. Long tail looks good tucked or untucked.",
    tags: ["white", "tshirt", "t shirt", "short sleeve", "women", "female"],
  },
  {
    id: "T11",
    company: "Nlife",
    name: "Bring on the Sunshine",
    price: 15,
    type: "short sleeve",
    color: "yellow",
    image: "/tshirts/bringOnTheSunshine.jpg",
    description: "Material wicks sweat & dries really fast. New, streamlined fit & shaped hem. Loose, fuller cut for complete comfort.",
    tags: ["yellow", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female"],
  },
  {
    id: "T12",
    company: "BORN",
    name: "Bonsai Tree Zen Buddhist T-Shirt",
    price: 15,
    type: "short sleeve",
    color: "blue",
    image: "/tshirts/bonsaiBlue.png",
    description: "Lightweight, classic fit, double-needle sleeve and bottom hem.",
    tags: ["blue", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "zen", "zen threads"],
  },
  {
    id: "T13",
    company: "ARTIST UNKNOWN",
    name: "Zen Leaf T-Shirt",
    price: 15,
    type: "short sleeve",
    color: "slate",
    image: "/tshirts/zenLeaf.jfif",
    description: "Centered- Great tshirt perfect for those who are centered through yoga, meditation or just being zen! Great gift for anyone!",
    tags: ["slate", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "zen", "zen threads"],
  },
  {
    id: "T14",
    company: "Lotus Zen Mandala Yoga Meditation",
    name: "Lotus Mandala Circle T-Shirt",
    price: 15,
    type: "short sleeve",
    color: "purple",
    image: "/tshirts/zenLotus.jfif",
    description:
      "Great gift for harmony, balance, exercise, asanas, ohm, om, taoist, nature lover, sacred geometry, boho, yoga art, asian, dao, diwali, hindu, Guatama Buddha, pilates, tai chi, marital arts, geometric mandala, spiritual flow, bohemian.",
    tags: ["purple", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female", "zen", "zen threads", "lotus"],
  },
  {
    id: "T15",
    company: "Wrinkled Hippie",
    name: "Tree of Life T-Shirt",
    price: 15,
    type: "short sleeve",
    color: "pink",
    image: "/tshirts/zenTree.jfif",
    description: "Gift for mindfulness peace seekers, moon gazers, people who love to meditate and be peaceful.",
    tags: ["pink", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female", "zen", "zen threads", "tree"],
  },
  {
    id: "T16",
    company: "ARTIST UNKNOWN",
    name: "All Heart No Ego T-Shirt",
    price: 15,
    type: "short sleeve",
    color: "white",
    image: "/tshirts/zenHeart.jfif",
    description:
      "Anyone who is spiritual, generous, kind, wears their heart on their sleeve, and is just a great person will love this All Heart No Ego Zen Mindful Yoga Premium Tee.",
    tags: ["white", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "zen", "zen threads", "heart"],
  },
  {
    id: "T17",
    company: "Yoga Astronaut Meditation Gifts",
    name: "Vintage Lotus Meditating Astronaut",
    price: 15,
    type: "short sleeve",
    color: "brown",
    image: "/tshirts/zenAstronaut.jfif",
    description:
      "Old school astronaut in lotus position design with solar system planets. Great gift for all who love stars, planets, space and astronauts. Astronomy, Yoga teachers and students will love this design.",
    tags: ["brown", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "zen", "zen threads", "astronaut"],
  },
  {
    id: "T18",
    company: "Ougedi",
    name: "Camoflage T-Shirt Army",
    price: 15,
    type: "short sleeve",
    color: "green",
    image: "/tshirts/camoGreen.jpg",
    description: "These T-Shirts are unisex and can be worn by anyone! Classic Casual fit.",
    tags: ["green", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "camo", "camoflage", "army"],
  },
  {
    id: "T19",
    company: "C9 Champion",
    name: "Modern Training Tee",
    price: 15,
    type: "short sleeve",
    color: "grey",
    image: "/tshirts/camoGrey.jpg",
    description: "Breathable fabric helps to keep you cool.",
    tags: ["grey", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "camo", "camoflage", "army"],
  },
  {
    id: "T20",
    company: "Kings Camo",
    name: "Classic Long Sleeve Tee",
    price: 15,
    type: "long sleeve",
    color: "brown",
    image: "/tshirts/camoForest.jpg",
    description:
      "The camouflage Classic Cotton Long Sleeve Tee is made of lightweight, 60/40 cotton/poly jersey. Includes tagless construction for increased comfort. Features a chest pocket and rib-knit collar and cuff.",
    tags: ["brown", "tshirt", "t shirt", "long sleeve", "graphic", "men", "male", "camo", "camoflage", "army"],
  },
  {
    id: "T21",
    company: "BMJL",
    name: "Casual Cute Shirt",
    price: 15,
    type: "short sleeve",
    color: "green",
    image: "/tshirts/camoGreen1.jpg",
    description: "The cute shirt for women is mainly made up of Polyester,will very lightweight,soft ,and breathable.",
    tags: ["green", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female", "camo", "camoflage", "army"],
  },
  {
    id: "T22",
    company: "Rothco",
    name: "Rothco Women's Short Sleeve",
    price: 15,
    type: "short sleeve",
    color: "pink",
    image: "/tshirts/camoPink.jpg",
    description: "Rothco is the foremost supplier of Military, tactical, survival and outdoor products.",
    tags: ["pink", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female", "camo", "camoflage", "army"],
  },
  {
    id: "T23",
    company: "KUOTAI",
    name: "Long Sleeve Camo T-shirts",
    price: 15,
    type: "long sleeve",
    color: "green",
    image: "/tshirts/camoLightGreen.jpg",
    description: "Long sleeve tops, round neck, pockets in the side, solid color and color block available, casual loose fitting woman tunic tops.",
    tags: ["green", "tshirt", "t shirt", "long sleeve", "graphic", "women", "female", "camo", "camoflage", "army"],
  },
  {
    id: "T24",
    company: "Marvel",
    name: "T'Challa Wakanda Forever",
    price: 20,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/comicWakanda.jfif",
    description: "Lightweight, Classic fit, Double-needle sleeve and bottom hem.",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "marvel", "black panther", "comic"],
  },
  {
    id: "T25",
    company: "Marvel",
    name: "Spider-Man: Beyond Amazing Multi-Logo T-Shirt",
    price: 20,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/comicSpiderman.jfif",
    description: "Lightweight, Classic fit, Double-needle sleeve and bottom hem.",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "marvel", "spiderman", "comic"],
  },
  {
    id: "T26",
    company: "Marvel",
    name: "Captain America Avengers Shield Comic T-Shirt",
    price: 20,
    type: "short sleeve",
    color: "blue",
    image: "/tshirts/comicCaptain.jfif",
    description: "Lightweight, Classic fit, Double-needle sleeve and bottom hem.",
    tags: ["blue", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "marvel", "captain", "america", "comic"],
  },
  {
    id: "T27",
    company: "DC Comics",
    name: "Batman Starry Night Style Painting T-Shirt",
    price: 20,
    type: "short sleeve",
    color: "black",
    image: "/tshirts/comicBatman.jfif",
    description: "Lightweight, Classic fit, Double-needle sleeve and bottom hem.",
    tags: ["black", "tshirt", "t shirt", "short sleeve", "graphic", "men", "male", "dc", "batman", "comic"],
  },
  {
    id: "T28",
    company: "DC Comics",
    name: "Wonder Woman Logo Adult Long-Sleeve T-Shirt",
    price: 20,
    type: "long sleeve",
    color: "red",
    image: "/tshirts/comicWonder.jpg",
    description: "This unisex adult long sleeve T shirt looks stylish on both men and women that will make it great for easy, everyday wear.",
    tags: ["red", "tshirt", "t shirt", "long sleeve", "graphic", "men", "male", "women", "female", "dc", "wonder", "woman", "comic"],
  },
  {
    id: "T29",
    company: "DC Comics",
    name: "The Flash Lightning Speed T-Shirt",
    price: 20,
    type: "short sleeve",
    color: "grey",
    image: "/tshirts/comicFlash.jfif",
    description: "Lightweight, Classic fit, Double-needle sleeve and bottom hem.",
    tags: ["grey", "tshirt", "t shirt", "short sleeve", "graphic", "women", "female", "dc", "flash", "comic"],
  },
];

export const pants = [
  {
    id: "P0",
    company: "Angor",
    name: "Jogger Pants",
    price: 20,
    type: "drawstring",
    color: "black",
    image: "/pants/black_0.png",
    description: "Material wicks sweat & dries really fast. New, streamlined fit & shaped hem. Loose, fuller cut for complete comfort.",
    tags: ["black", "pants", "drawstring", "jogger", "men", "male"],
  },
  {
    id: "P1",
    company: "Angor",
    name: "Cargo Pants",
    price: 15,
    type: "cargo",
    color: "brown",
    image: "/pants/brown_0.png",
    description:
      "SUPERIOR COMFORT FIT - Made of 100% heavyweight, soft jersey-knit cotton. Extra-strong seams for added durability. Tagless labeling eliminates chafing.",
    tags: ["brown", "pants", "cargo", "pockets", "men", "male"],
  },
  {
    id: "P2",
    company: "Angor",
    name: "Formal Pants",
    price: 20,
    type: "formal",
    color: "blue",
    image: "/pants/blue_0.png",
    description: "Sits at waist with a generous fit in seat and thigh; straight leg with reinforced knees.",
    tags: ["blue", "pants", "formal", "men", "male"],
  },
  {
    id: "P3",
    company: "Selovzz",
    name: "Lightweight Hiking Pants",
    price: 20,
    type: "casual",
    color: "gray",
    image: "/pants/casualString.jpg",
    description:
      "4-Way Stretch Running Pants --- Quick dry, breathable, lightweight, 4-way stretch fabric and comfortable tailored fit, durable enough to do any sports and casual wear.",
    tags: ["gray", "pants", "casual", "men", "male", "drawstring", "string"],
  },
  {
    id: "P4",
    company: "THWEI",
    name: "Mens Cargo Pants",
    price: 15,
    type: "casual",
    color: "khaki",
    image: "/pants/casualString1.jpg",
    description: "Great for all year round wear,suitabale for casual daily, street, school, workout, travel, hiking, climbing, running, gym, outdoors.",
    tags: ["khaki", "pants", "casual", "men", "male", "drawstring", "string"],
  },
  {
    id: "P5",
    company: "clothin",
    name: "Mens Workout Athletic Pants",
    price: 25,
    type: "casual",
    color: "blue",
    image: "/pants/casualString2.jpg",
    description: "Lightweight, breathable, quick dry, moisture wicking,extremely soft next to skin, keeps you cool and comfortable on the trail.",
    tags: ["blue", "pants", "casual", "men", "male", "drawstring", "string"],
  },
  {
    id: "P6",
    company: "Generic",
    name: "Palazzo Pants for Women",
    price: 13,
    type: "casual",
    color: "black",
    image: "/pants/casualElastic.jpg",
    description: "Women's high linen joggers cargo pants.",
    tags: ["black", "pants", "casual", "women", "female", "elastic"],
  },
  {
    id: "P7",
    company: "Amazon Aware",
    name: "Women's Pull-On Tapered Pant",
    price: 38,
    type: "casual",
    color: "brown",
    image: "/pants/casualString3.jpg",
    description: "Pull-on design with drawstring waistband closure.",
    tags: ["brown", "pants", "casual", "women", "female", "string", "drawstring"],
  },
  {
    id: "P8",
    company: "Hanes",
    name: "French Terry Pocket Pant",
    price: 16,
    type: "casual",
    color: "grey",
    image: "/pants/casualString4.jpg",
    description: "Relaxed-fit athletic pant in solid tone featuring wide ribbed waistband with adjustable drawcord.",
    tags: ["grey", "pants", "casual", "women", "female", "string", "drawstring"],
  },
];

export const caps = [
  {
    id: "C0",
    company: "Angor",
    name: "Classic Grey ",
    price: 10,
    type: "classic",
    color: "grey",
    image: "/caps/grey_0.png",
    description: "Chain stitched embroidery. Ventilating grommets for comfort and breathability",
    tags: ["grey", "cap", "classic", "men", "male"],
  },
  {
    id: "C1",
    company: "Angor",
    name: "Canvas Cap ",
    price: 20,
    type: "canvas",
    color: "blue",
    image: "/caps/blue_0.png",
    description: "Hook and Loop closure. Hand-wash only, if needed. One Size Fits Most",
    tags: ["blue", "cap", "canvas", "men", "male"],
  },
  {
    id: "C2",
    company: "Angor",
    name: "Crew Cap ",
    price: 15,
    type: "crew",
    color: "purple",
    image: "/caps/purple_0.png",
    description: "100% Cotton Made. Lightweight / Durable / Smooth",
    tags: ["purple", "cap", "crew", "men", "male"],
  },
  {
    id: "C3",
    company: "Fits Y'all",
    name: "Canvas Soft Mesh-Back Trucker Cap",
    price: 15,
    type: "mesh",
    color: "gold",
    image: "/caps/mesh.jpg",
    description: "Hook and Loop closure. Hand-wash only, if needed.",
    tags: ["gold", "cap", "mesh", "men", "male", "women", "female"],
  },
];
